using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Assets;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Skyrim.Assets;
using Mutagen.Bethesda.Synthesis;
using Noggog;

namespace WaterForENBPatcherCS;

public static class Program
{
    public const string OutputPlugin = "Ensrick Lux Water CS Patch.esp";

    private const int CompressedRecordFlag = 0x00040000;
    private static Lazy<Settings.Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        if (args is ["--self-test"])
        {
            return SelfTest.Run();
        }

        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch, new PatcherPreferences
            {
                ExclusionMods =
                [
                    ModKey.FromNameAndExtension(OutputPlugin),
                    ModKey.FromNameAndExtension("Synthesis.esp"),
                    ModKey.FromNameAndExtension("Requiem for the Indifferent.esp"),
                    ModKey.FromNameAndExtension("Occlusion.esp"),
                    ModKey.FromNameAndExtension("DynDOLOD.esm"),
                ],
            })
            .SetAutogeneratedSettings("settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, OutputPlugin)
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var listings = state.LoadOrder.ListedOrder
            .Where(x => x.Mod is not null)
            .ToList();

        var positions = listings
            .Select((listing, index) => (listing.ModKey, index))
            .ToDictionary(x => x.ModKey, x => x.index);

        var waterMain = listings.FirstOrDefault(x =>
            string.Equals(x.ModKey.FileName.String, _settings.Value.WaterForEnbModName, StringComparison.OrdinalIgnoreCase));

        if (waterMain?.Mod is null)
        {
            throw new InvalidOperationException(
                $"Water for ENB main plugin was not found in the active load order: {_settings.Value.WaterForEnbModName}");
        }

        var skippedNames = new HashSet<string>(_settings.Value.ModsToSkip, StringComparer.OrdinalIgnoreCase)
        {
            OutputPlugin,
        };

        var waterFamily = DiscoverWaterFamily(
            listings,
            waterMain.ModKey,
            _settings.Value.WaterFamilyPlugins,
            skippedNames);
        var candidateCells = new HashSet<FormKey>();
        var candidateWorldspaces = new HashSet<FormKey>();

        foreach (var listing in listings.Where(x => waterFamily.Contains(x.ModKey)))
        {
            foreach (var cell in listing.Mod!.EnumerateMajorRecords<ICellGetter>())
            {
                candidateCells.Add(cell.FormKey);
            }

            foreach (var worldspace in listing.Mod.EnumerateMajorRecords<IWorldspaceGetter>())
            {
                candidateWorldspaces.Add(worldspace.FormKey);
            }
        }

        state.PatchMod.ModHeader.Author = "Ensrick";
        state.PatchMod.ModHeader.Description =
            "Generated conflict patch: preserves the latest non-Water CELL/WRLD data and forwards Water for ENB water fields.";
        state.PatchMod.ModHeader.Flags |= SkyrimModHeader.HeaderFlag.Small;

        var patchedCells = PatchCells(state, candidateCells, waterFamily, skippedNames, positions);
        var patchedWorldspaces = PatchWorldspaces(
            state,
            candidateWorldspaces,
            waterFamily,
            skippedNames,
            positions);

        Console.WriteLine($"Water family ({waterFamily.Count}): {string.Join(", ", waterFamily.OrderBy(x => positions[x]).Select(x => x.FileName.String))}");
        Console.WriteLine($"Candidate records: {candidateCells.Count} CELL, {candidateWorldspaces.Count} WRLD");
        Console.WriteLine($"Patched records: {patchedCells} CELL, {patchedWorldspaces} WRLD");
        Console.WriteLine($"Output: {OutputPlugin} (ESL-flagged ESP)");
    }

    private static HashSet<ModKey> DiscoverWaterFamily(
        IReadOnlyList<IModListing<ISkyrimModGetter>> listings,
        ModKey waterMain,
        IReadOnlyCollection<string> configuredFamilyNames,
        IReadOnlySet<string> skippedNames)
    {
        var configured = new HashSet<string>(configuredFamilyNames, StringComparer.OrdinalIgnoreCase);
        var family = listings
            .Where(x => configured.Contains(x.ModKey.FileName.String))
            .Select(x => x.ModKey)
            .ToHashSet();
        family.Add(waterMain);
        var changed = true;

        while (changed)
        {
            changed = false;
            foreach (var listing in listings)
            {
                if (listing.Mod is null || family.Contains(listing.ModKey) || skippedNames.Contains(listing.ModKey.FileName.String))
                {
                    continue;
                }

                if (!listing.Mod.MasterReferences.Any(x => family.Contains(x.Master)))
                {
                    continue;
                }

                family.Add(listing.ModKey);
                changed = true;
            }
        }

        return family;
    }

    private static int PatchCells(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
        IEnumerable<FormKey> candidates,
        IReadOnlySet<ModKey> waterFamily,
        IReadOnlySet<string> skippedNames,
        IReadOnlyDictionary<ModKey, int> positions)
    {
        var patched = 0;

        foreach (var formKey in candidates.OrderBy(x => x.ModKey.FileName.String).ThenBy(x => x.ID))
        {
            var contexts = new FormLink<ICellGetter>(formKey)
                .ResolveAllContexts<ISkyrimMod, ISkyrimModGetter, ICell, ICellGetter>(state.LinkCache)
                .Where(x => positions.ContainsKey(x.ModKey) && !skippedNames.Contains(x.ModKey.FileName.String))
                .OrderBy(x => positions[x.ModKey])
                .ToList();

            if (!TryChooseContexts(contexts, formKey, waterFamily, out var baseContext, out var waterContext))
            {
                continue;
            }

            var patch = baseContext.GetOrAddAsOverride(state.PatchMod);
            CopyCellWaterFields(patch, waterContext.Record);
            ClearCompression(patch);
            patched++;
        }

        return patched;
    }

    private static int PatchWorldspaces(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
        IEnumerable<FormKey> candidates,
        IReadOnlySet<ModKey> waterFamily,
        IReadOnlySet<string> skippedNames,
        IReadOnlyDictionary<ModKey, int> positions)
    {
        var patched = 0;

        foreach (var formKey in candidates.OrderBy(x => x.ModKey.FileName.String).ThenBy(x => x.ID))
        {
            var contexts = new FormLink<IWorldspaceGetter>(formKey)
                .ResolveAllContexts<ISkyrimMod, ISkyrimModGetter, IWorldspace, IWorldspaceGetter>(state.LinkCache)
                .Where(x => positions.ContainsKey(x.ModKey) && !skippedNames.Contains(x.ModKey.FileName.String))
                .OrderBy(x => positions[x.ModKey])
                .ToList();

            if (!TryChooseContexts(contexts, formKey, waterFamily, out var baseContext, out var waterContext))
            {
                continue;
            }

            var patch = baseContext.GetOrAddAsOverride(state.PatchMod);
            CopyWorldspaceWaterFields(patch, waterContext.Record);
            ClearCompression(patch);
            patched++;
        }

        return patched;
    }

    private static bool TryChooseContexts<TMajor, TMajorGetter>(
        IReadOnlyList<IModContext<ISkyrimMod, ISkyrimModGetter, TMajor, TMajorGetter>> contexts,
        FormKey formKey,
        IReadOnlySet<ModKey> waterFamily,
        out IModContext<ISkyrimMod, ISkyrimModGetter, TMajor, TMajorGetter> baseContext,
        out IModContext<ISkyrimMod, ISkyrimModGetter, TMajor, TMajorGetter> waterContext)
        where TMajor : class, IMajorRecord, TMajorGetter
        where TMajorGetter : class, IMajorRecordGetter
    {
        baseContext = null!;
        waterContext = null!;

        var selectedWater = contexts.LastOrDefault(x => waterFamily.Contains(x.ModKey));
        var selectedBase = contexts.LastOrDefault(x => !waterFamily.Contains(x.ModKey));
        var current = contexts.LastOrDefault();

        if (selectedWater is null || selectedBase is null || current is null)
        {
            return false;
        }

        // A Water-family winner over an untouched origin record has no displaced
        // non-water changes to preserve. Avoid emitting thousands of no-value overrides.
        if (waterFamily.Contains(current.ModKey) && selectedBase.ModKey == formKey.ModKey)
        {
            return false;
        }

        baseContext = selectedBase;
        waterContext = selectedWater;
        return true;
    }

    internal static void CopyCellWaterFields(ICell target, ICellGetter source)
    {
        target.Water.SetTo(source.Water);
        target.WaterEnvironmentMap = source.WaterEnvironmentMap;
        target.WaterHeight = source.WaterHeight;
        target.Flags = target.Flags.SetFlag(
            Cell.Flag.HasWater,
            source.Flags.HasFlag(Cell.Flag.HasWater));
    }

    internal static void CopyWorldspaceWaterFields(IWorldspace target, IWorldspaceGetter source)
    {
        target.Water.SetTo(source.Water);
        target.LodWater.SetTo(source.LodWater);
        target.LodWaterHeight = source.LodWaterHeight;
        target.WaterEnvironmentMap = source.WaterEnvironmentMap is null
            ? null
            : new AssetLink<SkyrimTextureAssetType>(source.WaterEnvironmentMap.GivenPath);
    }

    private static void ClearCompression(IMajorRecord record)
    {
        record.MajorRecordFlagsRaw &= ~CompressedRecordFlag;
    }
}
